PostawNaMilionAzure/PostawNaMilionAzure/Controllers/AdminManageController.cs
using PostawNaMilionAzure.Models;
using PostawNaMilionAzure.Repository;
using PostawNaMilionAzure.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PostawNaMilionAzure.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminManageController : Controller
    {
        private IRepository<StepAddSubTotalValue> _stepAddSubTotalValue;
        private IExtendRepository<Game> _repositoryGame;
        private AzureContext _db = new AzureContext();

        public AdminManageController(IRepository<StepAddSubTotalValue> stepAddSubTotalValue,
            IExtendRepository<Game> repositoryGame)
        {
            _stepAddSubTotalValue = stepAddSubTotalValue;
            _repositoryGame = repositoryGame;
        }

        [HttpGet]
        public ActionResult SetStepTotalValue()
        {
            ViewBag.CurrentTotalValue = ((StepAddSubTotalValueRepository)_stepAddSubTotalValue).GetLastValue().StepValue;
            return View();
        }

        [HttpPost]
        public ActionResult SetStepTotalValue(StepAddSubTotalValue stepAddSubTotalValue)
        {
            if (!ModelState.IsValid)
            {
                return View(stepAddSubTotalValue);
            }

            stepAddSubTotalValue.DateAdd = DateTime.Now;
            _stepAddSubTotalValue.Add(stepAddSubTotalValue);
            return RedirectToAction("SetStepTotalValue");
        }

        //Get: Main page 
        public ActionResult Index()
        {
            var lastRegisterUser = _db.Users.Where(x => x.Id != "593ced2a-f41f-4483-9e62-731b531404b7").
                                                    Take(5).ToList();
            ViewBag.IsRegisterUser = lastRegisterUser.Count > 0 ? true : false;
            return View(lastRegisterUser);

        }

        [HttpGet]
        public ActionResult ValueGame(LastGameViewModel vM = null)
        {
            if (vM == null)
            {
                vM = new LastGameViewModel();

            }

            if (!ChechDate(vM.StarDate, vM.LastDate))
            {
                vM.StarDate = null;
                vM.LastDate = null;
                vM.CountGame = _repositoryGame.GetOverviewAll().ToList().Count();

            }
            else
            {
                Func<Game, bool> predicate = x => x.Date > DateTime.Parse(vM.StarDate) && x.Date < DateTime.Parse(vM.LastDate);
                vM.CountGame = _repositoryGame.GetOverviewAll(predicate).ToList().Count();
            }


            if (Request.IsAjaxRequest())
            {
                return PartialView("_ValueGame",vM);
            }


            return View(vM);
        }

        private bool ChechDate(string startDate, string endDate)
        {
            DateTime t1, t2;


            return DateTime.TryParse(startDate, out t1) && DateTime.TryParse(endDate, out t2);
        }
    }
}

PostawNaMilionAzure/PostawNaMilionAzure/Controllers/AdminManageQuestionController.cs
using PostawNaMilionAzure.Models;
using PostawNaMilionAzure.Repository;
using PostawNaMilionAzure.Utilties;
using PostawNaMilionAzure.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PostawNaMilionAzure.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminManageQuestionController : BaseController
    {
        private IExtendRepository<Question> _questionRepository;
        private IRepository<Answer> _answerRepository;
        private IRepository<CategoryDict> _categoryDictRepository;


        public AdminManageQuestionController(IExtendRepository<Question> repositoryQuestion
            , IRepository<Answer> repositoryAnswer, IRepository<CategoryDict> repositoryCategoryDict
            , ITarget mapper
            ) : base(mapper)
        {
            _questionRepository = repositoryQuestion;
            _answerRepository = repositoryAnswer;
            _categoryDictRepository = repositoryCategoryDict;
        }

        [HttpGet]
        public ActionResult AddQuestion()
        {
            ViewBag.InfoAddQuestion = TempData["isAdd"] == null ? "" : "Pytanie zostało dodane";
            QuestionViewModel vM = new QuestionViewModel(_categoryDictRepository);
            for (int i = 0; i < 4; i++)
            {
                vM.AnswerList[i] = new Answer();
            }
            vM.ActionName = "AddQuestion";
            return View(vM);
        }

        [HttpPost]
        public ActionResult AddQuestion(QuestionViewModel vM)
        {
            if (!ModelState.IsValid)
            {
                return View("AddQuestion", vM);
            }
            SaveAddEdditQuestion(vM, false);

            TempData["isAdd"] = "add";
            return RedirectToAction("AddQuestion");
        }

        [HttpGet]
        public ActionResult EditQuestion(int id)
        {
            QuestionViewModel vM = new QuestionViewModel(_categoryDictRepository);
            vM.ActionName = "EditQuestion";
            vM.Question = _questionRepository.GetIdAll(id);
            for (int i = 0; i < vM.Question.Answer.Count(); i++)
            {
                vM.AnswerList[i] = _answerRepository.GetID(vM.Question.Answer.ElementAt(i).Id);
            }
            return View(vM);
        }

        [HttpPost]
        public ActionResult EditQuestion(QuestionViewModel vM)
        {
            if (!ModelState.IsValid)
            {
                return View("EditQuestion", vM);
            }
            vM.AnswerList = vM.AnswerList.Select(x => { x.IsCorrect = false; return x; }).ToArray();

            SaveAddEdditQuestion(vM, true);

            return RedirectToAction("Category", "AdminManageCategory");
        }

        public ActionResult Question(int categoryID)
        {
            Func<Question, bool> predicate = x => x.CategoryDictId == categoryID;

            var vM = _questionRepository.GetOverview(predicate).ToList();
            if (Request.IsAjaxRequest())
            {
                return PartialView("_ListQUestion", vM);
            }
            return View(vM);

        }

        public ActionResult HiddenQuestion(int id)
        {
            var question = _questionRepository.GetID(id);
            question.IsHidden = !question.IsHidden;
            _questionRepository.Update(question);
            return new HttpStatusCodeResult(System.Net.HttpStatusCode.OK);
        }

        #region helpers

        public void SaveAddEdditQuestion(QuestionViewModel vM, bool isEdit)
        {
            vM.AnswerList[vM.isCorrectNumber].IsCorrect = true;
            var question = _mapper.GetItem<QuestionViewModel, Question>(vM);
            question.Answer = new List<Answer>();
            foreach (var answer in vM.AnswerList)
            {
                question.Answer.Add(answer);
            }

            if (isEdit)
            {
                _questionRepository.Update(question);
                question.Answer.ToList().ForEach(x => _answerRepository.Update(x));
                return;
            }

            _questionRepository.Add(question);

        }

        #endregion

    }
}

PostawNaMilionAzure/PostawNaMilionAzure/Controllers/AdminManageUserController.cs
using PostawNaMilionAzure.Models;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System;


namespace PostawNaMilionAzure.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminManageUserController : Controller
    {
        // GET: Admin
        private AzureContext db = new AzureContext();

        // GET: AdminManagUser
        public ActionResult Index()
        {
        
            return View(db.Users.Where(x => x.Id != "a0c6bb10-d343-4280-9929-b91076670465").ToList());
        }

        // GET: AdminManagUser/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser applicationUser = db.Users.Find(id);
            if (applicationUser == null)
            {
                return HttpNotFound();
            }
            return View(applicationUser);
        }

        // GET: AdminManagUser/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser applicationUser = db.Users.Find(id);
            if (applicationUser == null)
            {
                return HttpNotFound();
            }
            return View(applicationUser);
        }

        // POST: AdminManagUser/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName")] ApplicationUser applicationUser)
        {
            if (ModelState.IsValid)
            {
                db.Entry(applicationUser).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(applicationUser);
        }

        // GET: AdminManagUser/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser applicationUser = db.Users.Find(id);
            if (applicationUser == null)
            {
                return HttpNotFound();
            }
            return View(applicationUser);
        }

        // POST: AdminManagUser/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            ApplicationUser applicationUser = db.Users.Find(id);
            db.Users.Remove(applicationUser);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PostawNaMilionAzure/PostawNaMilionAzure/Controllers/GameController.cs
using Microsoft.AspNet.Identity;
using NLog;
using PostawNaMilionAzure.Exceptions;
using PostawNaMilionAzure.Models;
using PostawNaMilionAzure.Repository;
using PostawNaMilionAzure.Utilties;
using PostawNaMilionAzure.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PostawNaMilionAzure.Controllers
{
    public class GameController : Controller
    {
        private IExtendRepository<Question> _questionRepository;
        private IRepository<Answer> _answerRepository;
        private IRepository<CategoryDict> _categoryDictRepository;
        private ISessionManager _sessionManager;
        private IExtendRepository<Game> _gameRepository;
        private GameManager _gameManager;
        private static Logger _log;

        public GameController(IExtendRepository<Question> questionRepository, IRepository<Answer> answerRepository,
         IRepository<CategoryDict> categoryDictRepository, ISessionManager sessionManager,
         IExtendRepository<Game> gameRepository,
         IRepository<StepAddSubTotalValue> stepAddSubTotalValueRepository)
        {
            _questionRepository = questionRepository;
            _answerRepository = answerRepository;
            _categoryDictRepository = categoryDictRepository;
            _sessionManager = sessionManager;
            _log = LogManager.GetCurrentClassLogger();
            _gameRepository = gameRepository;
            _gameManager = new GameManager(_sessionManager,
                                            _categoryDictRepository,
                                            _questionRepository,
                                            _answerRepository,
                                            _gameRepository,
                                            stepAddSubTotalValueRepository);
        }
        public ActionResult NewGame()
        {
            return View();
        }

        public ActionResult Game()
        {
            //try
            //{
                _gameManager.NewGame();
                var vM = _gameManager.GetCategory();
                vM.IsCategory = true;
                return View(vM);
            //}
            //catch(Exception e)
            //{
            //    _log.Info("Gracz " + User.Identity.Name + " - " + e.Message);
            //    return RedirectToAction("Error", "Home");
            //}

        }

        public ActionResult LostGame()
        {
            if (_sessionManager.Get<string>(GameCommon.ErrorMessage) != null)
            {
                _log.Info("Gracz " + User.Identity.Name + " - " + _sessionManager.Get<string>(GameCommon.ErrorMessage));
                return PartialView("ErrorPage", _sessionManager.Get<string>(GameCommon.ErrorMessage));
            }
            if (User.Identity.IsAuthenticated)
            {
                _gameManager.SaveResult(User.Identity.GetUserId());
            }
            return View();
        }


        public ActionResult WinGame()
        {
            if (User.Identity.IsAuthenticated)
            {
                _gameManager.SaveResult(User.Identity.AuthenticationType);
            }
            return View();
        }

        [HttpPost]
        public ActionResult GetQuestion(int categoryID)
        {
            try
            {
                var vM = _gameManager.GetQuestion(categoryID);
                vM.IsCategory = false;
                return PartialView("_Question", vM);
            }
            catch (GameException e)
            {
                _log.Info("Gracz " + User.Identity.Name + " - " + e.Message);
                return PartialView("_ErrorPage", e.Message);

            }

        }

        public ActionResult GetCategory()
        {
            try
            {
                var vM = _gameManager.GetCategory();
                vM.IsCategory = true;
                return PartialView("_Question", vM);
            }
            catch (GameException e)
            {
                _log.Info("Gracz " + User.Identity.Name + " - " + e.Message);
                return PartialView("_ErrorPage", e.Message);
            }

        }

        public int SendAnswer(int questionID, Dictionary<string, string> answers)
        {
            var vM = _gameManager.GetResultAnswer(questionID, answers);
            return (int)vM.TypeResultGame;
        }

        public ActionResult CheckResult(int result)
        {
            return result == (int)TypeResultGame.LostGame ?
                RedirectToAction("LostGame") :
                RedirectToAction("WinGame");
        }

        public ActionResult ErrorPage(string message)
        {
            return View(message);
        }

        [Authorize]
        public ActionResult LastGame()
        {
            Func<Game, bool> predicate = x => x.UserId == User.Identity.GetUserId();
            var allGame = _gameRepository.GetOverviewAll(predicate).OrderByDescending(x => x.Date).ToList();
            return View(allGame);
        }

    }
}

PostawNaMilionAzure/PostawNaMilionAzure/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("css", required: false)
    <script type='text/javascript'>
        var appInsights = window.appInsights || function (config) {
            function r(config) { t[config] = function () { var i = arguments; t.queue.push(function () { t[config].apply(t, i) }) } }
            var t = { config: config }, u = document, e = window, o = 'script', s = u.createElement(o), i, f; for (s.src = config.url || '//az416426.vo.msecnd.net/scripts/a/ai.0.js', u.getElementsByTagName(o)[0].parentNode.appendChild(s), t.cookie = u.cookie, t.queue = [], i = ['Event', 'Exception', 'Metric', 'PageView', 'Trace', 'Ajax']; i.length;) r('track' + i.pop()); return r('setAuthenticatedUserContext'), r('clearAuthenticatedUserContext'), config.disableExceptionTracking || (i = 'onerror', r('_' + i), f = e[i], e[i] = function (config, r, u, e, o) { var s = f && f(config, r, u, e, o); return s !== !0 && t['_' + i](config, r, u, e, o), s }), t
        }({
            instrumentationKey: 'b0ed13db-20e6-403e-aedc-3996ed56acd2'
        });

        window.appInsights = appInsights;
        appInsights.trackPageView();
    </script>
    <meta name="description" content="The description of my page" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Postaw na Milion", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Nowa Gra", "Game", "Game")</li>
                    <li>@Html.ActionLink("Historia", "LastGame", "Game")</li>
                    <li>@Html.ActionLink("Kontakt", "Contact", "Home")</li>
                    @if (User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Panel Administratora", "Index", "AdminManage")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

PostawNaMilionAzure/PostawNaMilionAzure/Views/Shared/_LayoutAdmin.cshtml
@{
    ViewBag.Title = "Administracja";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-md-2 col-sm-12">
            <ul class="nav navbar-btn nav-admin-manage">
                <li>@Html.ActionLink("Informacje", "Category", "AdminManageCategory")</li>
                <li>@Html.ActionLink("Kategorie", "Category", "AdminManageCategory")</li>
                <li>@Html.ActionLink("Dodaj Kategorie", "AddCategory", "AdminManageCategory")</li>
                <li>@Html.ActionLink("Dodaj Pytanie", "AddQuestion", "AdminManageQuestion")</li>
                <li>@Html.ActionLink("Użytkownicy", "Index", "AdminManageUser")</li>
                <li>@Html.ActionLink("Jednostka obstawiania", "SetStepTotalValue", "AdminManage")</li>
                <li>@Html.ActionLink("Statystyka gier", "ValueGame", "AdminManage")</li>

                <li><a href="@Url.Content("~/elmah")">Logi</a></li>

            </ul>
        </div>
        <div class="col-md-10 col-sm-12">
            @RenderBody()

        </div>
    </div>
</div>

@section scripts{
    @RenderSection("scripts", required: false)
    }